# In this config file you can toggle specific features
# more options will be added in the future
core:
  # These values cannot be in decimal form!
  entitydistance: 25 # The max distance the plugin will show entity bossbar in (in blocks)
  blockdistance: 25 # The max distance the plugin will show block bossbar in (in blocks)
  update-delay: 5 # How frequently to update the BossBar, (in ticks)
  mode: "normal" # The mode of the plugin (normal, sneaking, hidden) (hidden mode will hide the bossbars, is useful when you want to display info somewhere else)
  default_state: "enabled" # Whether bossbars should be "disabled" by default or "enabled".
  bstats: true # whether to enable bsStats or not (recommended to keep on)

blocks:
  enabled: true
  redstoneinfo: true # Show RedStone power/status
  cropinfo: true # Show Crop age
  beehiveinfo: true # Show Honey in BeeHive/Nest
  smeltinfo: true # Show Smelt time
  containerinfo: true # Show Items in a container
  beaconinfo: true # Show Beacon effects
  spawnerinfo: true # Show Current spawning entity in spawner
  noteblockinfo: true # Show Instrument, tone and octave of NoteBlock
  farmlandinfo: true # Show Whether farmland is hydrated or not
  toolinfo: true # Show what the preferred tool to break the block is
  break-progress: true # BossBar only as of now, but shows progress of the block being broken (can be smooth or not depending on update delays)

entities:
  enabled: true
  ageinfo: true # Show Time left for entity to become adult
  ownerinfo: true # Show Name of the player who tamed the animal
  leashinfo: true # Show Whether entity is leashed or not
  healthinfo: true # Show health of entity
  professioninfo: true # Show profession of villager
  tntinfo: true # Show tnt time till explosion
  health-progress: true # BossBar only as of now, changes the progress of the bossBar according to health of entity

# the Worlds in which WIT is disabled.
world-blacklist:
  # - world_the_end

# The MATERIAL of the blocks to ignore, https://jd.papermc.io/paper/1.21.5/org/bukkit/material/package-summary.html
block-blacklist:
  - BARRIER
  - LIGHT
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID

# the ENTITY_TYPE of entities to ignore, https://jd.papermc.io/paper/1.21.5/org/bukkit/entity/EntityType.html
entity-blacklist:
  - ITEM
  - ITEM_DISPLAY
  - BLOCK_DISPLAY
  - INTERACTION
  - EVOKER_FANGS
  - EXPERIENCE_BOTTLE
  - EXPERIENCE_ORB
  - EXPERIENCE_BOTTLE
  - EXPERIENCE_ORB
  - FALLING_BLOCK
  - LIGHTNING_BOLT
  - MARKER
  - SPLASH_POTION
  - LINGERING_POTION
  - FIREBALL
  - SMALL_FIREBALL
  - SHULKER_BULLET
  - FIREWORK_ROCKET
  - EYE_OF_ENDER
  - SNOWBALL
  - ENDER_PEARL
  - DRAGON_FIREBALL
  - SPECTRAL_ARROW
  - ARROW
  - TRIDENT
  - WITHER
  - ENDER_DRAGON